#!/bin/bash 
git clone https://github.com/sabeehah123/java-docker.git
mvn clean pakcage 
java -jar hello-world-0.0.1-SNAPSHOT.jar 
docker rm -f $(docker 0.0.0.0:8080->8080/tcp 
docker build -t java-hello
docker run -d -p 
